version: '3.8'

networks:
    laravel:

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: my_laravel_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        command: >
            sh -c "php artisan serve --host=0.0.0.0 --port=8000"
        networks:
            - laravel

    mysql:
        image: mysql:8.0.21
        command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/init.sql
        container_name: mysql
        restart: unless-stopped
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "4306:3306"
        environment:
            MYSQL_DATABASE: laravel_notebook
            MYSQL_ROOT_PASSWORD: pass
            SERVICE_TAG: dev
            SERVICE_NAME: mysql
        networks:
            - laravel
